### ISSUE TITLE
URL+Extension should use String.hasSuffix instead of String.Contain for checking extension.

### ISSUE THREAD

**Issue by bomong** [khuong291/SourceSageTest#1]

**Comment by khuong291** [comment]
Hi @bomong,
No need, because url.pathExtension can check extension of the url. Using Array.Contain is enough.

<img width="599" alt="screen shot 2018-02-03 at 9 59 29 am" src="https://user-images.githubusercontent.com/11523438/35762432-20c065c6-08c9-11e8-863b-443a75acacce.png">

**Comment by hudsonnguyen** [comment]
My mistake, I misread array.contains to string.contains. Please close this.
